---
  # Ceph is special. We handle it here
  - name: (ceph) Install check and dependencies
    become: True
    apt:
      name:
        - ceph-dash
        - check-ceph-dash
        - ceph-exporter
      state: present
      update_cache: yes
      cache_valid_time: 1800

  - name: (ceph) Ensure that ceph-dash directory exists
    become: True
    file: path="/opt/ceph-dash" owner=root group=root mode=0755 state=directory

    #  - name: (ceph) Install ceph-dash runner
    #    become: True
    #    copy: src="{{ item }}" dest="/opt/ceph-dash/{{ item }}" owner=root group=root mode=0755
    #    with_items:
    #      - ceph-lodash.py
    #    notify: restart ceph-dash
    #
    #  - name: (ceph) Reload systemd
    #    become: True
    #    command: systemctl daemon-reload
    #    when: cservice.changed
    #    notify: restart ceph-dash

  - name: (ceph) Ensure that ceph user exists
    become: True
    user: name=ceph groups=www-data createhome=no append=yes shell=/bin/false

  - name: (ceph) Change permissions on ceph keyring so that the dashboard can access it
    become: True
    file: path=/etc/ceph/ceph.client.admin.keyring owner=root group=www-data mode=0640
    notify: restart ceph-dash
  
    #  - name: (ceph) Configure ceph check
    #    become: True
    #    copy: src="ceph-dash-config.json" dest="/opt/ceph-dash/config.json" owner=ceph group=www-data mode=0644

  - name: (ceph) Refresh ceph cluster config
    become: True
    shell: cat /etc/ceph/ceph.conf | sed 's/\/etc\/pve\/priv\/\$cluster\.\$name\.keyring/\/etc\/ceph\/ceph\.client\.admin\.keyring/g' > /opt/ceph-dash/ceph.conf && chown ceph:www-data /opt/ceph-dash/ceph.conf && chmod 0644 /opt/ceph-dash/ceph.conf
    changed_when: False

  - name: (ceph) Append ceph to list of checks
    set_fact: mon_icinga_checks="{{ mon_icinga_checks }} + ['ceph']"

  - name: (ceph) Append ceph to list of prometheus exporters
    set_fact: mon_prometheus_exporters="{{ mon_prometheus_exporters }} + ['ceph']"
