---
  - name: (ipmi) Install check
    become: True
    apt: name={{ item }} state=present update_cache=yes cache_valid_time=1800
    with_items:
      - check-ipmi-sensor

  - name: (ipmi) Save credentials
    become: True
    copy: src=ipmi.cfg dest=/etc/icinga2/freeipmi.conf owner=root group=nagios mode=0640

  - name: (ipmi) Detect IPMIs
    set_fact:
      ipmi_item: "ipmi {{ item }}"
    with_items: "{{ mon_check_ipmi_hosts|map(attribute='name')|list }}"
    register: ipmiappend

  - name: (ipmi) Append detected IPMIs to list of checks
    set_fact: mon_icinga_checks="{{ mon_icinga_checks }} + {{ ipmiappend.results | map(attribute='ansible_facts.ipmi_item') | list }}"
