---
  - name: (mysql) Install check
    become: True
    apt:
      name:
        - monitoring-plugins-standard
      state: present
      update_cache: yes
      cache_valid_time: 1800

  - name: (mysql) Detect databases
    set_fact:
      mysql_item: "mysql {{ item }}"
    with_items: "{{ mon_check_mysql|map(attribute='name')|list }}"
    register: mysqlappend

  - name: (mysql) Append detected websites to list of checks
    set_fact: mon_icinga_checks="{{mon_icinga_checks}} + {{ mysqlappend.results | map(attribute='ansible_facts.mysql_item') | list }}"

  - name: (mysql) Store credentials for check
    become: True
    template:
      src: my.cnf.j2
      dest: "/etc/icinga2/.my.{{ item.name }}.cnf"
      owner: nagios
      group: nagios
      mode: 0600
    with_items: "{{ mon_check_mysql }}"
    no_log: True
