---
  - name: (pgsql) Install check
    become: True
    apt:
      name:
        - monitoring-plugins-standard
      state: present
      update_cache: yes
      cache_valid_time: 1800

  - name: (pgsql) Detect databases
    set_fact:
      pgsql_item: "pgsql {{ item }}"
    with_items: "{{ mon_check_pgsql|map(attribute='name')|list }}"
    register: pgsqlappend

  - name: (pgsql) Append detected websites to list of checks
    set_fact: mon_icinga_checks="{{mon_icinga_checks}} + {{ pgsqlappend.results | map(attribute='ansible_facts.pgsql_item') | list }}"

  - name: (pgsql) Store credentials for check
    become: True
    template:
      src: pgcheck.conf.j2
      dest: "/etc/icinga2/.pgsql.{{ item.name }}"
      owner: nagios
      group: nagios
      mode: 0600
    with_items: "{{ mon_check_pgsql }}"
    no_log: True
