---
  - name: (power) Install check
    become: True
    apt:
      name:
        - check-power
      state: present
      update_cache: yes
      cache_valid_time: 1800

  - name: (power) Detect power strips
    set_fact:
      power_item: "power {{ item }}"
    with_items: "{{ mon_check_power_strips|map(attribute='name')|list }}"
    register: powerappend

  - name: (power) Append detected powerstrips to list of checks
    set_fact: mon_icinga_checks="{{ mon_icinga_checks }} + {{ powerappend.results | map(attribute='ansible_facts.power_item') | list }}"
