---
  - name: (sensors) Install check and lm-sensors
    become: True
    apt:
      name:
        - lm-sensors
        - check-lm-sensors
      state: present
      update_cache: yes
      cache_valid_time: 1800
    register: lmsensors

  - name: (sensors) Configure lm-sensors
    become: True
    command: sensors-detect --auto
    when: lmsensors.changed

  - name: (sensors) Install sensor name remapping file
    become: True
    copy: src=sensors-ansible.conf dest=/etc/sensors.d/sensors-ansible.conf owner=root group=root mode=0644

  - name: (sensors) Detect sensors
    set_fact:
      sensor_item: "sensors {{ item }}"
    with_items: "{{ mon_check_sensors|map(attribute='name')|list }}"
    register: sensorsappend

  - name: (sensors) Append detected sensors to list of checks
    set_fact: mon_icinga_checks="{{ mon_icinga_checks }} + {{ sensorsappend.results | map(attribute='ansible_facts.sensor_item') | list }}"
