---
  - name: (swport) Install check
    become: True
    apt: name={{ item }} state=present update_cache=yes cache_valid_time=1800
    with_items:
      - check-snmp-int

  - name: (swport) Detect switch ports
    set_fact:
      swport_item: "snmpif {{ item }}"
    with_items: "{{ mon_check_swport|map(attribute='if')|list }}"
    register: swportappend

  - name: (swport) Append detected swport to list of checks
    set_fact: mon_icinga_checks="{{ mon_icinga_checks }} + {{ swportappend.results | map(attribute='ansible_facts.swport_item') | list }}"
